use_frameworks!

target 'RKBluetoothLEKit_Example' do
  pod 'RKBluetoothLEKit', :path => '../'
end

target 'RKBluetoothLEKit_Tests' do
  pod 'RKBluetoothLEKit', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
