use_frameworks!

target 'RKBluetoothLEKit_Example', :exclusive => true do
  pod 'RKBluetoothLEKit', :path => '../'
end

target 'RKBluetoothLEKit_Tests', :exclusive => true do
  pod 'RKBluetoothLEKit', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
